=== ecell/libmoleculizer/src_OLD/install/standalone-xmloperator/data/dtdxml_1_0.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  DTDXML 1.0
  DTD for DTDXML documents
  Last update : 2002-01-20
  PUBLIC "-//xmloperator//DTD DTDXML 1.0//EN//XML"
  SYSTEM "http://www.xmloperator.net/dtd/dtdxml_1_0.dtd"
  Namespace : http://www.xmloperator.org/namespace/dtdxml
  Root element : dtd
-->

<!ELEMENT dtd (notationDecl*,(internalEntityDecl|externalEntityDecl)*,namespace*,noNamespace?,prefix*,attDefsPattern*,childrenPattern*,elementDecl+)>
<!ATTLIST dtd
  version CDATA #FIXED "1.0"
  dTDName CDATA #IMPLIED
  dTDVersion CDATA #IMPLIED
  dTDDescription CDATA #IMPLIED
  dTDPublicId CDATA #IMPLIED
  dTDSystemId CDATA #IMPLIED
  nsURIReference CDATA #IMPLIED
  rootElementDecl IDREF #IMPLIED
  lastUpdate CDATA #IMPLIED
>
<!-- rootElementDecl identity constraint : must reference an "elementDecl" element -->

<!ELEMENT notationDecl EMPTY>
<!ATTLIST notationDecl
  name NMTOKEN #REQUIRED
  publicId CDATA #IMPLIED
  systemId CDATA #IMPLIED
>

<!ELEMENT internalEntityDecl EMPTY>
<!ATTLIST internalEntityDecl
  name NMTOKEN #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT externalEntityDecl EMPTY>
<!ATTLIST externalEntityDecl
  name NMTOKEN #REQUIRED
  publicId CDATA #IMPLIED
  systemId CDATA #REQUIRED
  notationName NMTOKEN #IMPLIED
>

<!ELEMENT namespace EMPTY>
<!ATTLIST namespace
  id ID #REQUIRED
  uRIReference CDATA #REQUIRED
>

<!ELEMENT noNamespace EMPTY>
<!ATTLIST noNamespace
  id ID #REQUIRED
>

<!ELEMENT prefix EMPTY>
<!ATTLIST prefix
  id ID #REQUIRED
  prefix NMTOKEN #REQUIRED
  namespace IDREF #IMPLIED
>
<!-- namespace identity constraint : must reference a "namespace" element -->

<!ELEMENT attDefsPattern ((namespaceRef|namespacePrefix|attDef|attDefsPatternRef))+>
<!ATTLIST attDefsPattern
  id ID #REQUIRED
>

<!ELEMENT namespaceRef EMPTY>
<!ATTLIST namespaceRef
  namespace IDREF #REQUIRED
>
<!-- namespace identity constraint : must reference a "namespace" element  or a 'noNamespace" element -->

<!ELEMENT namespacePrefix EMPTY>
<!ATTLIST namespacePrefix
  prefix IDREF #REQUIRED
>
<!-- prefix identity constraint : must reference a "prefix" element whose "namespace" attribute is not empty -->

<!ELEMENT attDef EMPTY>
<!ATTLIST attDef
  prefix IDREF #IMPLIED
  localPartName NMTOKEN #REQUIRED
  type (cdata|id|idref|idrefs|entity|entities|nmtoken|nmtokens|enumeration|notation) "cdata"
  enumeration NMTOKENS #IMPLIED
  defaultType (required|implied|default|fixed) "implied"
  defaultValue CDATA #IMPLIED
  identityConstraint CDATA #IMPLIED
>
<!-- prefix identity constraint : must reference a "prefix" element -->
<!-- constraint : for type "enumeration" and "notation", the "enumeration" attribute contains one or more token(s) -->
<!-- constraint : for type other than "enumeration" or "notation", there is no "enumeration" attribute -->
<!-- constraint : for default type "required" and "implied", there is no "defaultValue" attribute -->
<!-- constraint : for default type "default" and "fixed", the "defaultValue" attribute contains one of the enumeration's token -->
<!-- constraint : for type other than "idref" or "idrefs", there is no "identityConstraint" attribute -->

<!ELEMENT attDefsPatternRef EMPTY>
<!ATTLIST attDefsPatternRef
  attDefsPattern IDREF #REQUIRED
>
<!-- attDefsPattern identity constraint : must reference an "attDefsPattern" element -->

<!ELEMENT childrenPattern (elementDeclRef|children|childrenPatternRef)+>
<!ATTLIST childrenPattern
  id ID #REQUIRED
  unaryOperator (one|zeroOrOne|zeroOrMore|oneOrMore) "one"
  binaryOperator (choice|seq) "choice"
>

<!ELEMENT childrenPatternRef EMPTY>
<!ATTLIST childrenPatternRef
  childrenPattern IDREF #REQUIRED
>
<!-- childrenPattern identity constraint : must reference a "childrenPattern" element  -->

<!ELEMENT children (elementDeclRef|children|childrenPatternRef)+>
<!ATTLIST children
  unaryOperator (one|zeroOrOne|zeroOrMore|oneOrMore) "one"
  binaryOperator (choice|seq) "choice"
>

<!ELEMENT mixed (elementDeclRef)*>
<!ATTLIST mixed
>

<!ELEMENT elementDeclRef EMPTY>
<!ATTLIST elementDeclRef
  unaryOperator (one|zeroOrOne|zeroOrMore|oneOrMore) "one"
  elementDecl IDREF #REQUIRED
>
<!-- elementDecl identity constraint : must reference an "elementDecl" element -->

<!ELEMENT elementDecl (((namespaceRef|namespacePrefix|attDef|attDefsPatternRef))*,(children|childrenPatternRef|mixed)?,elementDeclNote*)>
<!ATTLIST elementDecl
  id ID #REQUIRED
  prefix IDREF #IMPLIED
  localPartName NMTOKEN #REQUIRED
  contentType (empty|any|mixed|children) "empty"
>
<!-- prefix identity constraint : must reference a "prefix" element -->
<!-- constraint : for contentType "empty" and "any", there is no "children", "childrenPatternRef" neither "mixed" child element -->
<!-- constraint : for contentType "children", there is a "children" or "childrenPatternRef" child element -->
<!-- constraint : for contentType "mixed", there is a "mixed" child element -->

<!ELEMENT elementDeclNote (#PCDATA)>
<!ATTLIST elementDeclNote
  type (constraint|equivalence|use|comment) "constraint"
>

=== ecell/libmoleculizer/bin/xmloperator_2_3_0/data/dtdxml_1_0_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dtd PUBLIC "-//xmloperator//DTD DTDXML 1.0//EN//XML" "dtdxml_1_0.dtd">
<dtd dTDDescription="DTD for DTDXML documents" dTDName="DTDXML" dTDPublicId="-//xmloperator//DTD DTDXML 1.0//EN//XML" dTDSystemId="http://www.xmloperator.net/dtd/dtdxml_1_0.dtd" dTDVersion="1.0" lastUpdate="2002-01-20" nsURIReference="http://www.xmloperator.org/namespace/dtdxml" rootElementDecl="e_dtd"><namespace id="n_dtd" uRIReference="http://www.xmloperator.org/namespace/dtdxml"/><attDefsPattern id="a_id"><attDef defaultType="required" localPartName="id" type="id"/></attDefsPattern><attDefsPattern id="a_name"><attDef defaultType="required" localPartName="name" type="nmtoken"/></attDefsPattern><attDefsPattern id="a_qname"><attDef identityConstraint="must reference a &quot;prefix&quot; element" localPartName="prefix" type="idref"/><attDef defaultType="required" localPartName="localPartName" type="nmtoken"/></attDefsPattern><attDefsPattern id="a_unaryOperator"><attDef defaultType="default" defaultValue="one" enumeration="one zeroOrOne zeroOrMore oneOrMore" localPartName="unaryOperator" type="enumeration"/></attDefsPattern><attDefsPattern id="a_operators"><attDefsPatternRef attDefsPattern="a_unaryOperator"/><attDef defaultType="default" defaultValue="choice" enumeration="choice seq" localPartName="binaryOperator" type="enumeration"/></attDefsPattern><childrenPattern id="c_attDefs"><elementDeclRef elementDecl="e_namespaceRef"/><elementDeclRef elementDecl="e_namespacePrefix"/><elementDeclRef elementDecl="e_attDef"/><elementDeclRef elementDecl="e_attDefsPatternRef"/></childrenPattern><childrenPattern id="c_children" unaryOperator="oneOrMore"><elementDeclRef elementDecl="e_elementDeclRef"/><elementDeclRef elementDecl="e_children"/><elementDeclRef elementDecl="e_childrenPatternRef"/></childrenPattern><elementDecl contentType="children" id="e_dtd" localPartName="dtd"><namespaceRef namespace="n_dtd"/><attDef defaultType="fixed" defaultValue="1.0" localPartName="version"/><attDef localPartName="dTDName"/><attDef localPartName="dTDVersion"/><attDef localPartName="dTDDescription"/><attDef localPartName="dTDPublicId"/><attDef localPartName="dTDSystemId"/><attDef localPartName="nsURIReference"/><attDef identityConstraint="must reference an &quot;elementDecl&quot; element" localPartName="rootElementDecl" type="idref"/><attDef localPartName="lastUpdate"/><children binaryOperator="seq"><elementDeclRef elementDecl="e_notationDecl" unaryOperator="zeroOrMore"/><children unaryOperator="zeroOrMore"><elementDeclRef elementDecl="e_internalEntityDecl"/><elementDeclRef elementDecl="e_externalEntityDecl"/></children><elementDeclRef elementDecl="e_namespace" unaryOperator="zeroOrMore"/><elementDeclRef elementDecl="e_noNamespace" unaryOperator="zeroOrOne"/><elementDeclRef elementDecl="e_prefix" unaryOperator="zeroOrMore"/><elementDeclRef elementDecl="e_attDefsPattern" unaryOperator="zeroOrMore"/><elementDeclRef elementDecl="e_childrenPattern" unaryOperator="zeroOrMore"/><elementDeclRef elementDecl="e_elementDecl" unaryOperator="oneOrMore"/></children></elementDecl><elementDecl id="e_notationDecl" localPartName="notationDecl"><attDefsPatternRef attDefsPattern="a_name"/><attDef localPartName="publicId"/><attDef localPartName="systemId"/></elementDecl><elementDecl id="e_internalEntityDecl" localPartName="internalEntityDecl"><attDefsPatternRef attDefsPattern="a_name"/><attDef defaultType="required" localPartName="value"/></elementDecl><elementDecl id="e_externalEntityDecl" localPartName="externalEntityDecl"><attDefsPatternRef attDefsPattern="a_name"/><attDef localPartName="publicId"/><attDef defaultType="required" localPartName="systemId"/><attDef localPartName="notationName" type="nmtoken"/></elementDecl><elementDecl id="e_namespace" localPartName="namespace"><attDefsPatternRef attDefsPattern="a_id"/><attDef defaultType="required" localPartName="uRIReference"/></elementDecl><elementDecl id="e_noNamespace" localPartName="noNamespace"><attDefsPatternRef attDefsPattern="a_id"/></elementDecl><elementDecl id="e_prefix" localPartName="prefix"><attDefsPatternRef attDefsPattern="a_id"/><attDef defaultType="required" localPartName="prefix" type="nmtoken"/><attDef identityConstraint="must reference a &quot;namespace&quot; element" localPartName="namespace" type="idref"/></elementDecl><elementDecl contentType="children" id="e_attDefsPattern" localPartName="attDefsPattern"><attDefsPatternRef attDefsPattern="a_id"/><children unaryOperator="oneOrMore"><childrenPatternRef childrenPattern="c_attDefs"/></children></elementDecl><elementDecl id="e_namespaceRef" localPartName="namespaceRef"><attDef defaultType="required" identityConstraint="must reference a &quot;namespace&quot; element  or a 'noNamespace&quot; element" localPartName="namespace" type="idref"/></elementDecl><elementDecl id="e_namespacePrefix" localPartName="namespacePrefix"><attDef defaultType="required" identityConstraint="must reference a &quot;prefix&quot; element whose &quot;namespace&quot; attribute is not empty" localPartName="prefix" type="idref"/></elementDecl><elementDecl id="e_attDef" localPartName="attDef"><attDefsPatternRef attDefsPattern="a_qname"/><attDef defaultType="default" defaultValue="cdata" enumeration="cdata id idref idrefs entity entities nmtoken nmtokens enumeration notation" localPartName="type" type="enumeration"/><attDef localPartName="enumeration" type="nmtokens"/><attDef defaultType="default" defaultValue="implied" enumeration="required implied default fixed" localPartName="defaultType" type="enumeration"/><attDef localPartName="defaultValue"/><attDef localPartName="identityConstraint"/><elementDeclNote>for type &quot;enumeration&quot; and &quot;notation&quot;, the &quot;enumeration&quot; attribute contains one or more token(s)</elementDeclNote><elementDeclNote>for type other than &quot;enumeration&quot; or &quot;notation&quot;, there is no &quot;enumeration&quot; attribute</elementDeclNote><elementDeclNote>for default type &quot;required&quot; and &quot;implied&quot;, there is no &quot;defaultValue&quot; attribute</elementDeclNote><elementDeclNote>for default type &quot;default&quot; and &quot;fixed&quot;, the &quot;defaultValue&quot; attribute contains one of the enumeration's token</elementDeclNote><elementDeclNote>for type other than &quot;idref&quot; or &quot;idrefs&quot;, there is no &quot;identityConstraint&quot; attribute</elementDeclNote></elementDecl><elementDecl id="e_attDefsPatternRef" localPartName="attDefsPatternRef"><attDef defaultType="required" identityConstraint="must reference an &quot;attDefsPattern&quot; element" localPartName="attDefsPattern" type="idref"/></elementDecl><elementDecl contentType="children" id="e_childrenPattern" localPartName="childrenPattern"><attDefsPatternRef attDefsPattern="a_id"/><attDefsPatternRef attDefsPattern="a_operators"/><childrenPatternRef childrenPattern="c_children"/></elementDecl><elementDecl id="e_childrenPatternRef" localPartName="childrenPatternRef"><attDef defaultType="required" identityConstraint="must reference a &quot;childrenPattern&quot; element " localPartName="childrenPattern" type="idref"/></elementDecl><elementDecl contentType="children" id="e_children" localPartName="children"><attDefsPatternRef attDefsPattern="a_operators"/><childrenPatternRef childrenPattern="c_children"/></elementDecl><elementDecl contentType="children" id="e_mixed" localPartName="mixed"><children unaryOperator="zeroOrMore"><elementDeclRef elementDecl="e_elementDeclRef"/></children></elementDecl><elementDecl id="e_elementDeclRef" localPartName="elementDeclRef"><attDefsPatternRef attDefsPattern="a_unaryOperator"/><attDef defaultType="required" identityConstraint="must reference an &quot;elementDecl&quot; element" localPartName="elementDecl" type="idref"/></elementDecl><elementDecl contentType="children" id="e_elementDecl" localPartName="elementDecl"><attDefsPatternRef attDefsPattern="a_id"/><attDefsPatternRef attDefsPattern="a_qname"/><attDef defaultType="default" defaultValue="empty" enumeration="empty any mixed children" localPartName="contentType" type="enumeration"/><children binaryOperator="seq"><children unaryOperator="zeroOrMore"><childrenPatternRef childrenPattern="c_attDefs"/></children><children unaryOperator="zeroOrOne"><elementDeclRef elementDecl="e_children"/><elementDeclRef elementDecl="e_childrenPatternRef"/><elementDeclRef elementDecl="e_mixed"/></children><elementDeclRef elementDecl="e_elementDeclNote" unaryOperator="zeroOrMore"/></children><elementDeclNote>for contentType &quot;empty&quot; and &quot;any&quot;, there is no &quot;children&quot;, &quot;childrenPatternRef&quot; neither &quot;mixed&quot; child element</elementDeclNote><elementDeclNote>for contentType &quot;children&quot;, there is a &quot;children&quot; or &quot;childrenPatternRef&quot; child element</elementDeclNote><elementDeclNote>for contentType &quot;mixed&quot;, there is a &quot;mixed&quot; child element</elementDeclNote></elementDecl><elementDecl contentType="mixed" id="e_elementDeclNote" localPartName="elementDeclNote"><attDef defaultType="default" defaultValue="constraint" enumeration="constraint equivalence use comment" localPartName="type" type="enumeration"/><mixed/></elementDecl></dtd>
